### PR TITLE
ci: Upgrade Node.js version to 20.11.0

### LINKED ISSUE #7: Node 20
Warnings while building:

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: maxnowack/local-cache@5264a1d2bfeb46a0da90d572126772703bb68edf

### PR DESCRIPTION
**Pull request by Yaminyam**
close #7 
CleanShot 2024-02-06 at 19 35 25@2x
I upgraded the deprecated node16 version to the node20 version.
Once the changes are reflected, a new version must be distributed.

### CODE REVIEW

**Comment by maxnowack** [comment]
Hi @Yaminyam, I've been a bit busy lately and currently don't have the time to actively maintain this project. However, I've granted you write access so you can handle changes and even roll out new releases. Your contributions are much appreciated, and I trust your judgment in managing the project's development. Feel free to dive in with your proposed changes, and don't hesitate to reach out if you have any questions or need assistance.

**Review by ujuc — APPROVED** [review]
LGTM :+1:

**Comment by ujuc** [comment]
@maxnowack Hi, Could you please create a new version tag?

**Comment by Yaminyam** [comment]
@ujuc I have been given permission
I will create a new version after making a few additional modifications.

**Comment by kurly-jhlim** [comment]
> @ujuc I have been given permission I will create a new version after making a few additional modifications.

can_not_wait

**Comment by Yaminyam** [comment]
@kurly-jhlim @ujuc https://github.com/maxnowack/local-cache/releases/tag/v2
A new version has been released
Please let me know if you have any problems!

**Comment by kurly-jhlim** [comment]
> @kurly-jhlim @ujuc https://github.com/maxnowack/local-cache/releases/tag/v2 A new version has been released Please let me know if you have any problems!

It works properly for me, without any issues!
thanks!

**Pull request merged**
